# Server settings
server:
  port: 8084

# Database configuration
spring:
  application:
    name: ONELINK-SERVICE
  datasource:
    url: jdbc:postgresql://192.168.0.196:5432/OneLink
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: false